// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeKy3OVPFZxzKSTMF03JPSHb79luKca64',
    appId: '1:262153091353:web:75126235d26d8967802d88',
    messagingSenderId: '262153091353',
    projectId: 'mitra-rizki-admin',
    authDomain: 'mitra-rizki-admin.firebaseapp.com',
    storageBucket: 'mitra-rizki-admin.firebasestorage.app',
    measurementId: 'G-LJ62E1HF6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkzCjq9oe9KlLm2-GUzCZ90o7wVKOrgJ0',
    appId: '1:262153091353:android:87a68dc4575ac132802d88',
    messagingSenderId: '262153091353',
    projectId: 'mitra-rizki-admin',
    storageBucket: 'mitra-rizki-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjXT0OlrNRb9zDqhjRQj1QpfMvKHnOg84',
    appId: '1:262153091353:ios:431542926b3d5a41802d88',
    messagingSenderId: '262153091353',
    projectId: 'mitra-rizki-admin',
    storageBucket: 'mitra-rizki-admin.firebasestorage.app',
    iosBundleId: 'com.example.siramTumbuhCustomer',
  );
}
